export * from "./friends/friends.service";
// export * from "./friends/friends.service.spec";
export * from "./profile/profile.service";
// export * from "./profile/profile.service.spec";
export * from "./setprofile/setprofile.service";
// export * from "./setprofile/setprofile.service.spec";
// export * from "./friends/friends.service.spec";
// export * from "./profile/profile.service";
// export * from "./profile/profile.service.spec";
export * from "./otheruser/otheruser.service";
// export * from "./otheruser/otheruser.service.spec";
export * from "./workoutschedule/workoutschedule.service";
// export * from "./workoutschedule/workoutschedule.service.spec";
export * from "./registration/register.service";
